TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this

DB += caen_V965.template
DB += caen_V965Debug.template
DB += adc_module.template
DB += adc_channel.template
#----------------------------------------------------

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

